services:
  db:
    container_name: wp-backend-db
    image: mysql:8.0.33
    volumes:
      - ./import:/docker-entrypoint-initdb.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: not-so-secure
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: not-so-secure

  memcached:
    image: memcached:1.5

  php:
    depends_on:
      - db
      - memcached
    ports:
      - "8080:8080"
    image: bitpoke/wordpress-runtime:bedrock-php-8.1
    volumes:
      - ./:/app
      - ../wordpress:/app/web/app/plugins/nextpress
    env_file:
      - .env